const data = {
  product: [
    {
      _id: "1",
      name: "Adidas shoe",
      slug: "adidas-shoe",
      category: "Shoes",
      image: "/images/adidas-shoe1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 10,
      description: "an adidas shoe",
    },
    {
      _id: "2",
      name: "Puma shoe",
      slug: "puma-shoe",
      category: "Shoes",
      image: "/images/puma-shoe1.jpg",
      price: 100,
      countInStock: 10,
      brand: "Puma",
      rating: 3.0,
      numReviews: 9,
      description: "a puma shoe",
    },
    {
      _id: "3",
      name: "Nike short 1",
      slug: "nike-short-1",
      category: "Shorts",
      image: "/images/nike-short-black.jpg",
      price: 90,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "a Nike short",
    },
    {
      _id: "4",
      name: "Nike short 2",
      slug: "nike-short-2",
      category: "Shorts",
      image: "/images/nike-short-black.jpg",
      price: 90,
      countInStock: 10,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
      description: "a Nike short",
    },
  ],
};

export default data;
